services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/data/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=Gkdl3948
      - POSTGRES_DB=DonStart-test
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  api:
    build: backend
    env_file:
      - .env
    container_name: api
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - redis

volumes:
  postgres-db:
  redis-data: