"""uniq game info

Revision ID: 624b2953bcf5
Revises: ac5f019561fa
Create Date: 2024-06-18 08:58:32.417471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624b2953bcf5'
down_revision: Union[str, None] = 'ac5f019561fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Games', ['description'])
    op.create_unique_constraint(None, 'Games', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Games', type_='unique')
    op.drop_constraint(None, 'Games', type_='unique')
    # ### end Alembic commands ###
