"""add favourite games

Revision ID: 66213098d61e
Revises: b1877364f901
Create Date: 2024-07-05 12:19:15.954613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66213098d61e'
down_revision: Union[str, None] = 'b1877364f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites_table',
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('game_guid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_guid'], ['Games.guid'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['Users.guid'], ),
    sa.PrimaryKeyConstraint('user_guid', 'game_guid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites_table')
    # ### end Alembic commands ###
