"""set limits to str and add likes dislikes count to user

Revision ID: 6d4b4d3671ac
Revises: 624b2953bcf5
Create Date: 2024-06-18 16:20:47.658425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4b4d3671ac'
down_revision: Union[str, None] = '624b2953bcf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
