"""add role color

Revision ID: 9969115d8043
Revises: 35ab745901de
Create Date: 2024-06-29 13:56:42.025830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9969115d8043'
down_revision: Union[str, None] = '35ab745901de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Roles', 'color')
    # ### end Alembic commands ###
