"""added pictures for games and users

Revision ID: ac5f019561fa
Revises: c6a7aa80e076
Create Date: 2024-06-17 19:40:07.015462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5f019561fa'
down_revision: Union[str, None] = 'c6a7aa80e076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Games', sa.Column('img', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('profile_picture', sa.String(), server_default='some picture', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'profile_picture')
    op.drop_column('Games', 'img')
    # ### end Alembic commands ###
