"""init

Revision ID: b1877364f901
Revises: 
Create Date: 2024-06-30 20:42:22.627019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1877364f901'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_picture', sa.String(), server_default='some picture', nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Games',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('creator_guid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_guid'], ['Users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['Users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Votes',
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('game_guid', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_guid'], ['Games.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_guid'], ['Users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_guid', 'game_guid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Votes')
    op.drop_table('Roles')
    op.drop_table('Games')
    op.drop_table('Users')
    # ### end Alembic commands ###
